pgEdge:
  # -- Determines the name of resources in the pgEdge cluster. Many other
  # values are derived from this name, so it must be less than or equal to 26 characters in length.
  appName: pgedge
  # -- Whether to deploy cert-manager to manage TLS certificates for the cluster.
  # If false, you must provide your own TLS certificates by creating the secrets defined in
  # `clusterSpec.certificates.clientCASecret` and `clusterSpec.certificates.replicationTLSSecret`.
  provisionCerts: true
  # -- Configuration for each node in the pgEdge cluster. Each node will be deployed as a separate CloudNativePG Cluster.
  nodes: []
  # -- Configuration for nodes that are part of the pgEdge cluster, but managed externally to this Helm chart.
  # This can be leveraged for multi-cluster deployments or to wire up existing CloudNativePG Clusters to a pgEdge cluster.
  externalNodes: []
  # -- Whether or not to run the init-spock job to initialize the pgEdge nodes and subscriptions
  # In multi-cluster deployments, this should only be set to true on the last cluster to be deployed.
  initSpock: true
  # -- Docker image for the init-spock job. If not set, defaults to ghcr.io/pgedge/pgedge-helm-utils:v<chart-version>.
  # Override this for local development or to use a custom image.
  initSpockImageName: ""
  initSpockJobConfig:
    # -- Resources to allocate for the init-spock job. No resources are allocated by default.
    # Learn more at https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    resources: {}
    # -- Pod Security context for the init-spock job. Set to a Restricted profile by default.
    # Learn more at https://kubernetes.io/docs/concepts/security/pod-security-standards/
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
      fsGroup: 65532
    # -- Container Security context for the init-spock job. Set to a Restricted profile by default.
    # Learn more at https://kubernetes.io/docs/concepts/security/pod-security-standards/
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

  # -- Default CloudNativePG Cluster specification applied to all nodes, which can be overridden on a per-node basis
  # using the `clusterSpec` field in each node definition.
  clusterSpec:
    instances: 1
    imagePullPolicy: Always
    imageName: ghcr.io/pgedge/pgedge-postgres:17-spock5-standard
    certificates:
      clientCASecret: client-ca-key-pair
      replicationTLSSecret: streaming-replica-client-cert
    bootstrap:
      initdb:
        database: app
        owner: app
        encoding: UTF8
        postInitSQL: []
        postInitApplicationSQL:
          - CREATE EXTENSION spock;
        postInitTemplateSQL: []
    managed:
      roles:
        - name: admin
          ensure: present
          comment: Admin role
          login: true
          superuser: true
    postgresql:
      parameters:
        dynamic_shared_memory_type: "posix"
        wal_level: "logical"
        checkpoint_timeout: "15min"
        checkpoint_completion_target: "0.9"
        wal_sender_timeout: "5s"
        track_commit_timestamp: "on"
        hot_standby_feedback: "on"
        track_io_timing: "on"
        spock.enable_ddl_replication: "on"
        spock.include_ddl_repset: "on"
        spock.allow_ddl_from_functions: "on"
        spock.conflict_resolution: "last_update_wins"
        spock.save_resolutions: "on"
        spock.conflict_log_level: "DEBUG"
      shared_preload_libraries:
        - pg_stat_statements
        - snowflake
        - spock
      pg_hba:
        - hostssl app pgedge 0.0.0.0/0 cert
        - hostssl app admin 0.0.0.0/0 cert
        - hostssl app app 0.0.0.0/0 cert
        - hostssl all streaming_replica all cert map=cnpg_streaming_replica
      pg_ident:
        - local postgres admin
        - local postgres app
    projectedVolumeTemplate:
      sources:
        - secret:
            name: pgedge-client-cert
            items:
              - key: tls.crt
                path: pgedge/certificates/tls.crt
                mode: 0600
              - key: tls.key
                path: pgedge/certificates/tls.key
                mode: 0600
              - key: ca.crt
                path: pgedge/certificates/ca.crt
                mode: 0600

  # -- Array of extra Kubernetes resources to deploy alongside pgEdge (evaluated as templates).
  # Useful for deploying NetworkPolicies, PodMonitors, ConfigMaps, etc.
  extraResources: []
